trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  pythonVersion: '3.12'

  acrName: aiagentregistry2027

  backendRepository: ai-agent

  frontendRepository: ai-agent-ui

  azureServiceConnection: AI-Agent-ServiceConnection

############################################################
# BUILD
############################################################

stages:

- stage: Build
  displayName: "Build Stage"

  jobs:

  - job: BuildJob

    steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'

    - script: |
        python -m pip install --upgrade pip
      displayName: Upgrade pip

    - script: |
        pip install -r requirements.txt
      displayName: Install Dependencies

    - script: |
        python --version
        pip --version
      displayName: Verify Python

    - script: |
        python -m compileall src
      displayName: Compile Project

############################################################
# QUALITY
############################################################

- stage: Quality
  displayName: "Quality Checks"

  dependsOn: Build

  jobs:

  - job: Lint

    steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'

    - script: |
        pip install -r requirements.txt
      displayName: Install Dependencies

    - script: |
        black --check .
      displayName: Black

    - script: |
        ruff check .
      displayName: Ruff

############################################################
# TEST
############################################################

- stage: Testing
  displayName: "Unit Testing"

  dependsOn: Quality

  jobs:

  - job: Tests

    steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'

    - script: |
        pip install -r requirements.txt
      displayName: Install Dependencies

    - script: |
        python -m pytest tests/unit \
          --cov=src \
          --cov-report=term-missing \
          --cov-report=xml \
          --cov-fail-under=10
      displayName: Run Unit Tests

    - task: PublishCodeCoverageResults@2
      displayName: Publish Code Coverage
      inputs:
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage.xml'

############################################################
# PACKAGE
############################################################

- stage: Package
  displayName: Package

  dependsOn: Testing

  jobs:

  ##########################################################
  # Backend Image
  ##########################################################

  - job: BackendImage

    displayName: Build Backend Docker Image

    pool:
      vmImage: ubuntu-latest

    steps:

    - task: AzureCLI@2

      displayName: Build & Push Backend

      inputs:

        azureSubscription: $(azureServiceConnection)

        scriptType: bash

        scriptLocation: inlineScript

        inlineScript: |

          az acr login --name $(acrName)

          docker build \
            -f docker/backend.Dockerfile \
            -t $(acrName).azurecr.io/ai-agent:latest \
            -t $(acrName).azurecr.io/ai-agent:$(Build.BuildId) . || exit 1

          docker push $(acrName).azurecr.io/ai-agent:latest || exit 1

          docker push $(acrName).azurecr.io/ai-agent:$(Build.BuildId) || exit 1

  ##########################################################
  # Frontend Image
  ##########################################################

  - job: FrontendImage

    displayName: Build Frontend Docker Image

    dependsOn: BackendImage

    pool:
      vmImage: ubuntu-latest

    steps:

    - task: AzureCLI@2

      displayName: Build & Push Frontend

      inputs:

        azureSubscription: AI-Agent-ServiceConnection

        scriptType: bash

        scriptLocation: inlineScript

        inlineScript: |

          az acr login --name aiagentregistry2027

          docker build \
            -f docker/frontend.Dockerfile \
            -t $(acrName).azurecr.io/ai-agent-ui:latest \
            -t $(acrName).azurecr.io/ai-agent-ui:$(Build.BuildId) . || exit 1

          docker push $(acrName).azurecr.io/ai-agent-ui:latest || exit 1

          docker push $(acrName).azurecr.io/ai-agent-ui:$(Build.BuildId) || exit 1